apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: enterprise-system-20260625-135156-6649l0i7o29k-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: enterprise-system-20260625-135156-6649l0i7o29k.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: enterprise-system-20260625-135156-6649l0i7o29k-service
            port:
              number: 80
